# User Settings | Edit there as per required

title: yauuume
url: "http://yauuu.me"
baseurl: ""

# This will show up at the top of index page
site_heading: >
    yauuume <span class="faded">'s blog</span>

email: guillaume@chenuet.fr
author: Guillaume Chenuet
# This description will show up in google search results
# (for index page) etc.
description: >
    Some notes - Guillaume Chenuet

# This will what will show against &copy; in the footer
copyright: yauuume
# Toggle your short bio, which will displayed on your index page
# Just toggle it and run jekyll again to see
intro: false         # Tip: Remove the span from site_heading if intro is set to true
# This will be displayed in your intro
#short_bio: >
#    Welcome! This is <span>accent</span>, a mobile friendly theme for Jekyll. The main feature of this
#    theme is that you can change the accent color. Refer the
#    <a class="underline different-highlight" href="http://ankitsultana.me/accent/documentation.html">
#        Documentation
#    </a>
#    to know how.

permalink: /:title.html

# Comments are powered by disqus
comments: false

# keep about_stub roughly 12 words long for best results
# This will show up at the bottom of each post
# Note that about_footer should be true if you want
# to see author information at the bottom of each post
about_stub: >
    Make it simple, but significant.

about_footer: true

twitter_username: gchenuet
github_username: gchenuet
resume_url: guillaume.chenuet.fr

favicon: true
favicon_location: "images/gc.png"

profile_picture: "images/gc.png"
#paginate: 1
#paginate_path: "/page/:num"
tracking_id:  UA-56034830-1

# Social Stuff | open graph and twitter cards
og_image: "images/1.jpg" # This will show in facebook thumbnails
twitter_image: "http://yauuu.me/images/1.jpg" # This will show in twitter cards

####################################
####################################
####################################
### Build Settings | Don't Touch ###
####################################
####################################
####################################

markdown: kramdown

gems:
    - jekyll-paginate

sass:
    style: compressed
    sass_dir: _sass

# Scopes
defaults:
    -
        scope:
            path:   ""
            type:   "pages"
        values:
            layout: "page"
    -
        scope:
            path:   ""
            type:   "posts"
        values:
            layout: "post"

exclude: [vendor] # For travis ci
