# Site settings
title: Yauuume
email: contact@yauuu.me
description: > # this means to ignore newlines until "baseurl:"
        Some notes about my work.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yauuu.me" # the base hostname & protocol for your site
twitter_username: gchenuet
github_username:  gchenuet

# Build settings
markdown: kramdown
